### ISSUE TITLE
tab_width=0?

### ISSUE THREAD

**Issue by azz** [josephfrazier/editorconfig-to-prettier#1]
Is it valid for tab width to be set to zero? If it is, is it intentionally omitted from output?

**Comment by josephfrazier** [comment]
This was discussed a bit in https://github.com/prettier/prettier/pull/2760#discussion_r137447715. Here was my response at the time:

> Hmm, it looks like [tab_width](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties/98f8059ac82af0bea2d5af5f64f0dcc79c015ab1#tab_width) and [max_line_length](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties/98f8059ac82af0bea2d5af5f64f0dcc79c015ab1#max_line_length) must be positive. I suppose someone could set `indent_size` to 0, but I'm not sure if that edge case is worth supporting right now. At least, I haven't had time to put effort into it.

I'll add that since the config translation has now been pulled out into this package, it should be easier to implement/test support for `indent_size=0`.
