### ISSUE TITLE
[feature request] support converting more options

### ISSUE THREAD

**Issue by celluj34** [josephfrazier/editorconfig-to-prettier#21]
Hello;

I recently opened an issue (https://github.com/prettier/plugin-xml/issues/697) about why I had to duplicate settings in my .editorconfig and .prettierrc.json. I see that this is the (as far as I can tell) official library that prettier itself uses to convert editorconfig files.

My question is thus: if I wanted to be able to convert more settings from .editorconfig (namely `trailingComma`, `xmlWhitespaceSensitivity`, and `xmlQuoteAttributes`), is that something that would be supported?

**Comment by celluj34** [comment]
Looks like I forgot I opened a similar issue already (#9) so if the answer is the same, just let me know, thanks!

**Comment by josephfrazier** [comment]
Hi @celluj34, yeah, the answer is the same, sorry. Hope it's not too painful keeping the two files in sync! Maybe you could remove the `.editorconfig` and rely solely on `.prettierrc.json`? Or would that not provide the same level of functionality to you?

**Comment by celluj34** [comment]
We are using this file for a few other formats (C#, bicep, typescript, xml, yml), but prettier isn't being used for all of them. So unfortunately it looks like we'll still need both.

Thanks again, maybe next time I'll remember to check the issues first 😅

**Comment by josephfrazier** [comment]
That makes sense, no worries about the duplicate issue! This repo doesn't get that much traffic :P

**Comment by josephfrazier** [comment]
Hi @celluj34 , the code in this repo has been moved into Prettier's repo, so if you'd like to re-open this issue/question over there, feel free! See https://github.com/prettier/prettier/pull/15394 for details
