### ISSUE TITLE
Add some more details to the README

### ISSUE THREAD

**Issue by polarathene** [josephfrazier/editorconfig-to-prettier#6]
Hi, I've been looking into Prettier and been going over issues about `.editorconfig` support, one was about line endings and had your PR referenced. This repo README isn't clear on how this is used?

Is it a plugin to Prettier or does Prettier use it by default, do I just include it in my package.json dev dependencies and it works or do I need to run a command manually in the terminal?

I've had mixed information about `.editorconfig` support, there are some old deadlinks to docs or Prettier's github repo README that were about `.editorconfig` support but have disappeared. I've come across [this](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options) in the official Prettier docs but it says that some properties aren't supported. Are these properties related to what this project is doing or does Prettier support `.editorconfig` by default bar those properties and your project caters to them(all?).

Clarifying these details in this repo's README would really help new users like myself to Prettier that want to use or at least understand what the actual .editorconfig support is like. 

I'm guessing the lack of information means either this is not meant to be a repo users should bother about(if used by Prettier under the hood), editorconfig support for Prettier isn't popular(or the default support in it's docs is enough for most), or this is meant to be straight forward to use.

**Comment by josephfrazier** [comment]
Hi @polarathene, thanks for the good questions!

> Is it a plugin to Prettier or does Prettier use it by default, do I just include it in my package.json dev dependencies and it works or do I need to run a command manually in the terminal?

Prettier does use this repo to help provide its EditorConfig support, so you don't need to do anything special to use it (other than whatever the Prettier documentation says, if anything).

> I've had mixed information about `.editorconfig` support, there are some old deadlinks to docs or Prettier's github repo README that were about `.editorconfig` support but have disappeared. I've come across [this](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options) in the official Prettier docs but it says that some properties aren't supported. Are these properties related to what this project is doing or does Prettier support `.editorconfig` by default bar those properties and your project caters to them(all?).

Yes, the properties supported by Prettier correspond to those supported in this project. I know there's not much/any documentation here, but I'm hoping that you can get an idea of the functionality by looking at the source code (`index.js`) and tests (`test.js`). I'd be happy to consider any pull requests improving the documentation, as well!

**Comment by polarathene** [comment]
> I'd be happy to consider any pull requests improving the documentation, as well!

I think this issue clarifies the purpose of the repo and clears up any confusion, so you could just link to this issue or something like:

> Prettier support for [EditorConfig](http://editorconfig.org/). Prettier uses this package internally, users can refer to the supported EditorConfig properties [here](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath-options).

**Comment by josephfrazier** [comment]
Just updated the readme with a link here, thanks!

https://github.com/josephfrazier/editorconfig-to-prettier/commit/d318af7bb690aece1aad68a612c8beec05f2c4f1?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
