### ISSUE TITLE
Support "max_line_length=off"

### ISSUE THREAD

**Issue by chipironcin** [josephfrazier/editorconfig-to-prettier#7]
Editorconfig supports `off` as a valid value for `max_line_length` (see https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#user-content-max_line_length)

Current code only sets the Prettier property `printWidth` if `max_line_length !== "off"`:
```
  if (editorConfig.max_line_length && editorConfig.max_line_length !== "off") {
    result.printWidth = editorConfig.max_line_length;
  }
```

Ideally `max_line_length = "off"` should be supported, maybe with a very high value. Also other non-numeric values for it should be discarded.

I can raise a PR if this issue makes sense to the author and contributors. Please leave your feedback ;)

**Comment by josephfrazier** [comment]
That makes sense to me, @chipironcin , I'd love to see a PR for this!

**Comment by willmendesneto** [comment]
@josephfrazier This change is already added to the package's codebase. Would you mind closing this issue, please?

**Comment by josephfrazier** [comment]
@willmendesneto can you clarify how it has already been added? There haven't been any [commits to this repository](https://github.com/josephfrazier/editorconfig-to-prettier/commits/master) since this issue was opened.

**Comment by celluj34** [comment]
@josephfrazier 

I believe they are referencing https://github.com/josephfrazier/editorconfig-to-prettier/pull/3/files which only makes it ignored.

**Comment by josephfrazier** [comment]
I'm trying to remember the context from 3+ years ago, but I believe the original request was to set `result.printWidth` to a very high value, or possibly preferably a special value that `prettier` interprets to mean `Infinity`, but it's not clear whether that would have the desired effect, according to https://prettier.io/docs/en/options.html#print-width:

> For readability we recommend against using more than 80 characters:
> 
> In code styleguides, maximum line length rules are often set to 100 or 120. However, when humans write code, they don’t strive to reach the maximum number of columns on every line. Developers often use whitespace to break up long lines for readability. In practice, the average line length often ends up well below the maximum.
> 
> Prettier’s printWidth option does not work the same way. It is not the hard upper allowed line length limit. It is a way to say to Prettier roughly how long you’d like lines to be. Prettier will make both shorter and longer lines, but generally strive to meet the specified printWidth.
> 
> Remember, computers are dumb. You need to explicitly tell them what to do, while humans can make their own (implicit) judgements, for example on when to break a line.
> 
> In other words, don’t try to use printWidth as if it was ESLint’s [max-len](https://eslint.org/docs/rules/max-len) – they’re not the same. max-len just says what the maximum allowed line length is, but not what the generally preferred length is – which is what printWidth specifies.

**Comment by celluj34** [comment]
Ha, yes it was a long time ago. Sorry to necro such an old thread, but I've been running into this lately.

Does Prettier even support max_line_length=off? I couldn't find anything definitive either way.

**Comment by josephfrazier** [comment]
> https://www.youtube.com/watch?v=Zmp_--Oow5o

It's all good, happy to help if I can!

> Does Prettier even support max_line_length=off? I couldn't find anything definitive either way.

No, based on what I quoted in my previous message, Prettier _cannot_ support `max_line_length=off`, given that it _prefers_ to make lines the given `printWidth`. However, if you can elaborate on the difficulties you're having, maybe we can find another way to solve your problem. Have you tried raising the `max_line_length` to the highest value you're willing to tolerate on your screen?

**Comment by josephfrazier** [comment]
> but I could be convinced to use a high value like 9999 instead

Well... it sounds like this could result in Prettier collapsing a bunch of lines into one really long line, based on the docs quoted above:

> Prettier will make both shorter and longer lines, but generally strive to meet the specified printWidth.

So, I'm not sure if it's a good idea after all, might need to open that issue on the Prettier repo to discuss the implications.

**Comment by celluj34** [comment]
That is a good point - although I haven't seen any problems with the XML files I'm working with.

I would assume line length is context-dependent, as in it wouldn't try to put several JS lines delimited by a semicolon in a single line, but I don't know their internals.

Please let me know if you need anything from me!

**Comment by josephfrazier** [comment]
I just opened [an issue in the Prettier repo](https://github.com/prettier/prettier/issues/14514) and tagged you in it, we'll see what the other maintainers say!

**Comment by celluj34** [comment]
Nice! Thank you!

**Comment by celluj34** [comment]
Yep, I've been watching! Thanks for getting it all done. Once that part's complete I just need VSCode to upgrade the version of prettier it's using...

**Comment by josephfrazier** [comment]
Great, hopefully we're close to having this fixed for you 👍🏻

**Comment by josephfrazier** [comment]
@celluj34, https://github.com/prettier/prettier/pull/14516 was merged, meaning that the next release of Prettier should include this fix, unless it gets reverted for some reason.

**Comment by josephfrazier** [comment]
Prettier v2.8.5 has been released with the fix! https://github.com/prettier/prettier/blob/ddf3b43c33e2e98f6413b5232ad623876d96738e/CHANGELOG.md#support-max_line_lengthoff-when-parsing-editorconfig-14516-by-josephfrazier
