### ISSUE TITLE
How do I provide a value for the prettier config item `xmlWhitespaceSensitivity`?

### ISSUE THREAD

**Issue by celluj34** [josephfrazier/editorconfig-to-prettier#9]
Title.

I have SVG and XML files to format, but they are not respecting my tab width rules. I believe this is due to [the whitespace rules](https://github.com/prettier/plugin-xml#whitespace), so how can I provide this rule from my .editorconfig file?

**Comment by josephfrazier** [comment]
If I understand correctly, `xmlWhitespaceSensitivity` is an option for [prettier/plugin-xml](https://github.com/prettier/plugin-xml/tree/fd0047c56a27b94d2abb6798208bbf99f2fcdd6b#configuration), but not for editorconfig. This project is meant to support translating editorconfig options to prettier options, not for providing a way to specify arbitrary options within the editorconfig file. I'd recommend configuring `xmlWhitespaceSensitivity` in one of the standard locations for Pretter configuration, as described [here](https://prettier.io/docs/en/configuration.html), and then it will be taken into account alongside the editorconfig options.

Let me know if that doesn't make sense to you, or if I'm mistaken, etc!

**Comment by celluj34** [comment]
Yeah, that makes sense, and it does work (i.e., providing the value I need). I was just hoping to avoid having an entire file to provide a single value to prettier.

**Comment by josephfrazier** [comment]
ah, I see. If you're in an environment where you could remove the `.editorconfig` file and replace it with the equivalent prettier config, that could keep your file count down, but I don't know if other people/systems are relying on the `.editorconfig` being there

**Comment by celluj34** [comment]
Unfortunately I am using the editorconfig for other files as well, not just as a source for prettier options, so I can't remove it.

I suppose we can close this - you're right, I don't think this lib should be responsible for supporting non-standard editorconfig settings, I'll just have to live with it lol.

**Comment by josephfrazier** [comment]
Yeah... I wouldn't want to encourage people to put stuff in their `.editorconfig` that isn't part of the EditorConfig specification, so I'll close this. Thanks for bringing it up, though!
